"""create orders table

Revision ID: 305fdded3737
Revises: 
Create Date: 2026-07-23 12:30:47.357066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305fdded3737'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=40), nullable=False),
    sa.Column('client_id', sa.String(length=20), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('carrier', sa.String(length=30), nullable=False),
    sa.Column('origin_city', sa.String(length=80), nullable=False),
    sa.Column('destination_city', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('product_category', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order_value_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_promo', sa.Integer(), nullable=False),
    sa.Column('promo_discount_pct', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=15), nullable=False),
    sa.Column('warehouse', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_carrier'), 'orders', ['carrier'], unique=False)
    op.create_index('ix_orders_carrier_status', 'orders', ['carrier', 'status'], unique=False)
    op.create_index('ix_orders_category_date', 'orders', ['product_category', 'order_date'], unique=False)
    op.create_index(op.f('ix_orders_client_id'), 'orders', ['client_id'], unique=False)
    op.create_index(op.f('ix_orders_order_date'), 'orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=True)
    op.create_index(op.f('ix_orders_product_category'), 'orders', ['product_category'], unique=False)
    op.create_index(op.f('ix_orders_region'), 'orders', ['region'], unique=False)
    op.create_index(op.f('ix_orders_sku'), 'orders', ['sku'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_warehouse'), 'orders', ['warehouse'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_warehouse'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_sku'), table_name='orders')
    op.drop_index(op.f('ix_orders_region'), table_name='orders')
    op.drop_index(op.f('ix_orders_product_category'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_date'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_id'), table_name='orders')
    op.drop_index('ix_orders_category_date', table_name='orders')
    op.drop_index('ix_orders_carrier_status', table_name='orders')
    op.drop_index(op.f('ix_orders_carrier'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
